development:
  adapter: postgresql
  database: trala_dev
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: trala_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: trala
  pool: 5
  timeout: 5000