development:
  adapter: postgresql
  database: trala_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: trala_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: trala_production
  pool: 5
  timeout: 5000


